#!/usr/bin/env bash
#cript that:
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

file="/var/run/myscript.pid"

trap 'echo "I hate the kill command"; sudo rm "$file"; exit' SIGTERM SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT


touch "$file"
echo "$$" > "$file"

while true
do
	echo "To infinity and beyond"
	sleep 2
done
