#!/usr/bin/env bash
# my_process manager script

arg="$1"

if [[ "$arg" == "start" ]]
then
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [[ "$arg" == "stop" ]]
then
	pkill -f manage_my_process
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [[ "$arg" == "restart" ]]
then
	pkill -f manage_my_process
	rm /var/run/my_process.pid
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
