#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd.
#Your script should only display:
#username
#user id
#Home directory path for the user

while true
do
	cut -d ':' -f 1,3,6 /etc/passwd
	break
done
