#!/usr/bin/env bash
#This script displays Best School 10 times,
#but for the 9th iteration, displays Best School and then Hi on a new line.

str="Best School"
counter=0

while [[ counter -ne 10 ]]; do
	echo "$str"
	if [[ counter -eq 8 ]]; then
		echo "Hi"
	fi
	(( counter++ ))
done
