#! /usr/bin/env bash
#loops...,

str="Best School"
counter=0

while [[ counter -ne 10 ]]; do
	if [[ counter -eq 3 ]]; then
		echo bad luck
	elif [[ counter -eq 7 ]]; then
		echo good luck
	else
		echo "$str"
	fi
	(( counter++ ))
done
